### ISSUE TITLE
產生出來的URL不合邏輯

### ISSUE THREAD

**Issue by pcchou** [BirkhoffLee/shortener#1]
![515](https://cloud.githubusercontent.com/assets/5615415/6058398/fbb5d13c-ad61-11e4-9419-c349e20b707d.png)
看圖(?

**Comment by birkhofflee** [comment]
不然什麼才叫有邏輯(?

**Comment by pcchou** [comment]
ummmmmmmmmmmmmm
請看/前面

**Comment by pcchou** [comment]
應該是 http://s.irkhoff.com/ 的 $newURL 沒設好？

**Comment by birkhofflee** [comment]
喔喔 我以為你說 a1132 = =

**Comment by pcchou** [comment]
XDDDDD

**Comment by birkhofflee** [comment]
好了
