### ISSUE TITLE
建議把各種設定獨立出一個檔案，方便用 .gitignore 管理

### ISSUE THREAD

**Issue by pcchou** [BirkhoffLee/shortener#3]
config.sample.php 在 repo 裡面
config.php 設在 .gitignore

**Comment by birkhofflee** [comment]
這是啥

**Comment by s3131212** [comment]
.gitignore 是避免 Git 把資料同步到 Repo 裡面，放在 config.php 使用者容易忘記改，放到 config.sample.php 時，使用者就會記得要重新命名成 config.php 並修改內容了， Wordpress 就是這種方法

**Comment by pcchou** [comment]
#6

**Comment by birkhofflee** [comment]
OK
