### ISSUE TITLE
自訂字串不能為空

### ISSUE THREAD

**Issue by pcchou** [BirkhoffLee/shortener#4]
槓 騙我(X

![517](https://cloud.githubusercontent.com/assets/5615415/6058552/64d85cb0-ad63-11e4-81b3-ea8e81e8c82a.png)

**Comment by birkhofflee** [comment]
....

**Comment by birkhofflee** [comment]
OK拉

**Comment by birkhofflee** [comment]
= =
...................

**Comment by birkhofflee** [comment]
好了..
